name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Add MSBuild to path
        uses: microsoft/setup-msbuild@v2

      - name: Build
        run: .\build.bat

      - name: Create NSIS installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: NSIS installer
          path: build_nsis/install-test-*-win64.exe

      - name: Create WIX installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: WIX installer
          path: build_wix/install-test-*-win64.msi
